### ISSUE TITLE
Google Drive doesn’t support symlinks, so all.1.new.gz doesn’t get copied

### ISSUE THREAD

**Issue by sideshowbarker** [gkiefer/backup2l#1]
Google Drive doesn’t support symlinks, so when I copy a set of backup2l-generated files to my Google Drive storage, the `all.1.new.gz` file doesn’t get copied.

I suspect that other services such as Amazon Cloud Drive may also lack support for symlinks.

I use [the rclone tool](https://github.com/ncw/rclone) to copy backups to Google Drive and then to copy them back again, so the problem I have is, that `all.1.new.gz` symlink doesn’t get round-tripped.

So I would like for backup2l to either just always create `all.1.new.gz` by copying rather than symlinking, or to at least provide an option for doing that.

**Comment by gkiefer** [comment]
Basically, this option already exists. You may add something like this
to your POST_BACKUP function:

  for LINK in `find $BACKUP_DIR -type l`; do 
    TARGET=`realpath $LINK`
    rm $LINK
    cp -a $TARGET $LINK
  done

Regards,

Gundolf Kiefer

**Comment by sideshowbarker** [comment]
Ah yeah, I had forgotten about the `POST_BACKUP` function—thanks, will try that!

**Comment by sideshowbarker** [comment]
(Going ahead and closing this as resolved to my satisfaction.)
