### ISSUE TITLE
difference between ver. 1.5 and 1.6

### ISSUE THREAD

**Issue by scialo** [gkiefer/backup2l#10]
what difference?

**Comment by arnowelzel** [comment]
See here:
https://github.com/gkiefer/backup2l/commit/33e813de4d0ec108a26816c4cb6c4630f68cc005

And the parents of this commit:
https://github.com/gkiefer/backup2l/commit/22060ea7e36bff3520989e7ae974a70fa3f45aca
https://github.com/gkiefer/backup2l/commit/eec315704d7e9d4ffaaec9e4c900a2bd1cf2e3da
