### ISSUE TITLE
Integrate gzip/pigz dynamic driver

### ISSUE THREAD

**Issue by hbeni** [gkiefer/backup2l#11]
Hello Gundolf,
some time ago i wrote a dynamic Driver that is capable of automatically selecting pigz over gzip in case it is installed on the System. The patch proposed also changed the Default driver from gzip to pigz_or_gzip, so the backup is performed "out of the box" with the most performance available.

See my old proposal: https://sourceforge.net/p/backup2l/patches/20/
I think the patch does not apply cleanly anymore, but should be staightforward enough to easily be adjusted.

With best regards,
Beni

**Comment by gkiefer** [comment]
Thank you for the patch and the suggestion.

The PGZ driver is contained in the current version:
https://github.com/gkiefer/backup2l/blob/461f446fdfc01d9a98b0a41a66baca5df6ea20ba/first-time.conf#L391

The present convention in backup2l is that a driver creates its archive distinctly in the one format it is written for. The pigz_or_gzip driver would disrupt this convention. but not provide significant new functionality wrt DRIVER_TAR_PIGZ.

To keep backup2l simple (yet configurable and extensible) I prefer to not integrate this into the mainline version.
