### ISSUE TITLE
Not found in archive if filename contains [ or ]

### ISSUE THREAD

**Issue by plabong** [gkiefer/backup2l#12]
File with "[" or "]" in filename could not be restored
Driver = DRIVER_TAR
`  tar: path/Privat xy/\\[Untitled\\].pdf: Not found in archive`

**Comment by boppy** [comment]
I found that there are two problems handling weird filenames. I also found a fix but I think it might brake something else...

**Testing**
I created a directory with six weird named files in it:
```bash
echo "space in filename" > "name with spaces".txt 
echo "round brackets"    > "name-with-r(brackets).txt"
echo "square brackets"   > "name-with-s[brackets].txt"
echo "with backslash"    > "name-with-back\slash.txt"
echo "colon"             > "name-with-:collon.txt"
echo "asterisk"          > "name-with-*asterisk.txt"
```
---

**Files containing a backslash**
They *are* in fact inside the backup but also print an error - but also are restored if I restore `/home/`
```
Checking TOC of archive file (< real file, > archive entry)...
  4c4
  < /home/boppy/backuptest/files/name-with-back\slash.txt
  ---
  > /home/boppy/backuptest/files/name-with-back\\slash.txt

[...]

Backup       Date       Time  |  Size   | Skipped  Files+D |  New  Obs. | Err.
------------------------------------------------------------------------------
test-weird-names.1 2018-09-24 10:09 |      1K |       0        7 |    7     0 |    1
```
To fix that I simply added a second sed expression to kill double-backslashes in https://github.com/gkiefer/backup2l/blob/master/backup2l#L50:
```diff
< FILTER_UNIFY_NAME="sed 's#\\\\[0-7]\{3\}#?#g;   s#[^a-zA-Z0-9_ .$%:~/=+\#\-]#?#g'"
> FILTER_UNIFY_NAME="sed -e 's#\\\\[0-7]\{3\}#?#g;   s#[^a-zA-Z0-9_ .$%:~/=+\#\-]#?#g' -e 's/\\\\\\\\/\\\\/g'"
```
---

**Files containing *asterisk* (`*`) or *square brackets* (`[]`)**
The fix I found is to reduce a sed in https://github.com/gkiefer/backup2l/blob/master/backup2l#L1023-L1026:
```diff
<            grep -a "^$ARCH:" $BACKUP_DIR/$TMP.located \
<                | sed -e "s#^$ARCH: /##" -e 's#\([][*?]\)#\\\1#g' \
<                > $BACKUP_DIR/$TMP.curlist
<                # The second sed expression escapes special glob(7) characters ([]*?).

>            grep -a "^$ARCH:" $BACKUP_DIR/$TMP.located \
>                | sed "s#^$ARCH: /##" \
>                > $BACKUP_DIR/$TMP.curlist
```

I think that @gkiefer had something in mind while doing that `glob(7)` replace/escape, but I cannot find a problem.

If you want me to, I can provide that as a pull request if you don't see it braking something ;)

**Comment by gkiefer** [comment]
Thank you @boppy for the comments and investigations.

Did I understand correctly, that all your test cases worked with the second patch applied to https://github.com/gkiefer/backup2l/blob/master/backup2l#L1023-L1026? If so, we should apply that.

Actually, I had a reason for that replace/escape, but I cannot recall exactly which one. It must be related with some driver. However, my opinion today is that it is a good/better design to pass $TMP.curlist unmodified to the driver and eventually solve any problems inside the respective driver.

Can you provide a pull request? Thank you!

It may perhaps break the functionality in individual drivers. But that will be fixable afterwards.

**Comment by boppy** [comment]
I totally agree. And yes, with my latest testcase + latest fix everything's working. I am planning to creating I more in-depth test case

I will provide a PR for that not later than this weekend.

**Comment by boppy** [comment]
Hmm, found one more bug in listing/comparing that I want to fix. This will add a slight delay...

**Comment by boppy** [comment]
Okay, to keep this going:

The back and forth with listing, checking, and extracting makes handling of this kind of names very, very unhandy.

With the two fixed lines above I am able to backup and restore the mentioned file list. ***BUT*** only full directory extracting works:

```
./backup2l -c backup2l-test.conf -r '/home/boppy/backuptest/files/*'
```
only restores 3 of my 6 files, `*[\` are not restored. With

```
./backup2l -c backup2l-test.conf -r '/home/boppy/backuptest/files'
```
The full directory with all six files is restored.

I think I have identified every single place where directory listings are made and processed. The problem is that if I add an escape in one place, it destroys listing or processing at an other place.

So until now I was not able to fully fix this. Since I can only spend a senseful amount of time on this on the weekends, my question is: Do you want me to provide a PR with this limitations or should I continue working on this? I feel that, in order to fix this, some additional code lines are needed. I hope to provide them next weekend. In fact my "limitation" is already existing and makes nothing worse, but I don't like push half-ready code ;-)

**Comment by boppy** [comment]
Okay, my bad! Extracting does not follow glob-rules but regex...

```bash
backup2l -c backup2l-test.conf -l 'txt$'
# or
backup2l -c backup2l-test.conf -l '\['
# or
backup2l -c backup2l-test.conf -l '\\'
# or
backup2l -c backup2l-test.conf -l "/home/boppy/backuptest/files/name-with-..brackets..txt"
```
The only thing not working is the colon. Might be because the "time" entries do contain those or the grep output... It always catches everything on
```bash
backup2l/backup2l -c backup2l-test.conf -l '\:'
```

**Comment by gkiefer** [comment]
Thank you @boppy !

I believe merge #15 fixes this properly.
