### ISSUE TITLE
Place option --no-recursion before -T

### ISSUE THREAD

**Issue by plabong** [gkiefer/backup2l#18]
The option `--no-recursion` should be placed before option `-T`.

affected: `DRIVER_TAR( )`, `DRIVER_TAR_GZ( )` and `DRIVER_TAR_BZ2( )` 

See: [Debian Bug 829738#10](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829738#10)

**Comment by gkiefer** [comment]
This has been fixed by #16 .
