### ISSUE TITLE
Misleading warning

### ISSUE THREAD

**Issue by Al-** [gkiefer/backup2l#24]
Great tool!! I love it and use it on 6 raspberry pi. It is so great that I dare to comment on a minor thing, a misleading warning.

`backup2l -s` can be run by a non-root user (and without sudo) as long as the backup directory is readable; the output is correct. However, there is a  _WARNING: Volume is or was locked by another instance of 'backup2l'_., followed by instructions how to correct. I would have expected no warning or a warning that backup2l needs to be run by root. The correct hint for this warning is at the top of the backup2l output: _/usr/sbin/backup2l: line 348: /var/backup/XXX.lock: Permission denied_

**Comment by gkiefer** [comment]
Thank you for the report.

The fix (and proper solution) is to let the tool stop with an error in this case. Leaving `backup -s` running without a successful lock can result in other faulty behavior.
