### ISSUE TITLE
Ignore permissions and ownership on restore

### ISSUE THREAD

**Issue by blair-robertson** [gkiefer/backup2l#8]
Hi,

I am running backup2l via cygwin on Windows and it works well (I have to use the latest 1.6-pre2 for a problem in 1.5 that I now forget)

I had a situation recently where I was attempting to perform a restore onto a new laptop and the ownership and permissions basically failed badly. I presume this has more to do with cygwin's permission management than anything else. 

For the content I was backing up, not having the permissions was not really problem - the content is most important.

For the actual files themselves I can override the DRIVER_TAR_GZ and remove the `--same-permission --same-owner` arguments for `tar` at :
https://github.com/gkiefer/backup2l/blob/071ce97847fe1c0fd267097968bb903153187a56/backup2l#L207

But there is not anything I can do for the directories:
https://github.com/gkiefer/backup2l/blob/071ce97847fe1c0fd267097968bb903153187a56/backup2l#L1012-L1013

I was thinking that if these 3 lines where extracted to a separate function, then that function could be overridden in the conf file if required.

thanks

**Comment by blair-robertson** [comment]
Something like this (not tested!) change:
https://github.com/blair-robertson/backup2l/commit/36c9e78604eee3b9fa8427dec35416ae8433f243

**Comment by gkiefer** [comment]
What exactly does "fail badly" mean? I can imagine two solutions:

a) Add a configuration option like RESTORE_ATTRS=[1|0, default=1] , which deactivates the mentioned two lines if set to 0.

b) Rephrase the lines so that they fail silently in case of problems (would not require a new option).
