### ISSUE TITLE
Cannot restore from tgz_split

### ISSUE THREAD

**Issue by MacFizz** [gkiefer/backup2l#9]
Hello
I'm trying to restore files from a pretty big archive file.
Unfortunately, even though all the files are present, i get this:
Active files in <all.1147>: 7192
  found in all.1147:       0   ( 7192 left)
  found in all.1146:       0   ( 7192 left)
  found in all.1145:       0   ( 7192 left)
  found in all.1144:       0   ( 7192 left)
  found in all.1143:       0   ( 7192 left)
  found in all.1142:       0   ( 7192 left)
  found in all.1141:       0   ( 7192 left)
  found in all.114:        0   ( 7192 left)
  found in all.113:        0   ( 7192 left)
  found in all.112:        0   ( 7192 left)
  found in all.111:        1   ( 7191 left)
  found in all.11:         0   ( 7191 left)
  found in all.1:       7191   (    0 left)

Cannot access archive file(s) of the following backup(s):
  all.111
  all.1

Nothing has been restored.

Am I missing something ?

**Comment by MacFizz** [comment]
Might be a problem with the tar_gz driver.
I managed to recover the datas using cat /archives/all.1.tg_split/* | tar zxpvf -
So the files themselves are fine, however, restoring them with backup2l seems to be impossible.

Any clues ?

**Comment by gkiefer** [comment]
The problem appears to be related to the DRIVER_TAR_GZ_SPLIT driver, which is not part of the software itself, just provided as a template in the sample configuration file.

It would be great if someone out there who uses this or a similar driver could help out here.

**Comment by bccox** [comment]
I believe that any driver in the configuration file itself needs to be registered in the USER_DRIVER_LIST variable (also in the config file).  For example:

USER_DRIVER_LIST="DRIVER_TAR_GZ_SPLIT"

**Comment by gkiefer** [comment]
I agree with @bccox 's comment.

Closing this issue, which appears to be solved or outdated.
